import type { ShowcaseProduct } from "../components/product-showcase-section";

export const KIOSK_SHOWCASE_PRODUCTS: readonly ShowcaseProduct[] = [
  {
    title: "Kiosk System",
    tagline: "SELF-ORDERING, PETPOOJA SYNC",
    image: "/kiosk.png",
    checkpoints: [
      "BRANDED SELF-ORDER FLOW",
      "PETPOOJA MENU SYNC",
      "RAZORPAY AT CHECKOUT",
      "KITCHEN TICKETS AUTO-SENT",
      "LIVE IN DAYS, NOT MONTHS",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
  {
    title: "PetPooja Integration",
    tagline: "NATIVE POS SYNC, ZERO DOUBLE ENTRY",
    image: "/kiosk.png",
    checkpoints: [
      "TWO-WAY MENU SYNC",
      "MODIFIERS & ADD-ONS MAPPED",
      "ORDER STATUS IN REAL TIME",
      "NO MANUAL RE-ENTRY",
      "BUILT FOR RESTAURANT OPS",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
  {
    title: "Razorpay Payments",
    tagline: "UPI, CARDS, AND WALLETS BUILT IN",
    image: "/kiosk.png",
    checkpoints: [
      "UPI, CARDS & WALLETS",
      "INSTANT PAYMENT CONFIRMATION",
      "AUTOMATIC SETTLEMENT TRACKING",
      "FEWER COUNTER INTERRUPTIONS",
      "PCI-COMPLIANT CHECKOUT",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
  {
    title: "Custom Branding",
    tagline: "YOUR LOGO, YOUR COLORS, YOUR FLOW",
    image: "/kiosk.png",
    checkpoints: [
      "CUSTOM UI & COLOR SYSTEM",
      "MENU LAYOUT TUNED TO YOU",
      "UPSELL SCREENS BUILT IN",
      "ON-BRAND CUSTOMER EXPERIENCE",
      "NO GENERIC TEMPLATES",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
  {
    title: "Order Analytics",
    tagline: "REAL-TIME SALES AND PEAK HOUR INSIGHTS",
    image: "/kiosk.png",
    checkpoints: [
      "TOP SELLERS BY HOUR",
      "AVERAGE ORDER VALUE TRACKING",
      "RUSH-HOUR DEMAND SIGNALS",
      "PROMOTION PERFORMANCE",
      "ONE DASHBOARD VIEW",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
  {
    title: "Multi-Terminal Support",
    tagline: "SCALE ACROSS COUNTERS AND LOCATIONS",
    image: "/kiosk.png",
    checkpoints: [
      "MULTIPLE KIOSKS PER OUTLET",
      "CENTRAL MENU MANAGEMENT",
      "BRANCH-LEVEL REPORTING",
      "SAME PRICING EVERYWHERE",
      "BUILT FOR CHAINS",
    ],
    href: "/kiosk",
    linkLabel: "View Kiosk",
  },
];

export const HRMS_SHOWCASE_PRODUCTS: readonly ShowcaseProduct[] = [
  {
    title: "Entropia HRMS",
    tagline: "FACE SCAN ATTENDANCE, ONE-CLICK PAYROLL",
    image: "/hrms.png",
    checkpoints: [
      "FACE SCAN CHECK-IN",
      "ATTENDANCE AUTO-MARKED",
      "ONE-CLICK PAYROLL RUN",
      "EPF, ESIC & TDS FILED",
      "REPLACES PAGARBOOK",
    ],
    href: "/hrms",
    linkLabel: "View HRMS",
  },
  {
    title: "Formula Engine",
    tagline: "CUSTOM SALARY RULES, LIVE DEDUCTIONS",
    image: "/hrms.png",
    checkpoints: [
      "CUSTOM PAY FORMULAS",
      "BASIC, HRA & INCENTIVES",
      "OVERTIME AUTO-CALCULATED",
      "LIVE DEDUCTION RULES",
      "NO SPREADSHEET OVERRIDES",
    ],
    href: "/hrms",
    linkLabel: "Explore payroll",
  },
  {
    title: "Multi-Branch Command",
    tagline: "EVERY OUTLET LIVE, ONE DASHBOARD",
    image: "/hrms.png",
    checkpoints: [
      "ALL BRANCHES IN ONE VIEW",
      "LIVE ATTENDANCE STATUS",
      "PAYROLL PROGRESS TRACKING",
      "COMPLIANCE ALERTS",
      "BUILT FOR MULTI-OUTLET OPS",
    ],
    href: "/hrms",
    linkLabel: "See multi-branch",
  },
  {
    title: "Face Scan Attendance",
    tagline: "NO BUDDY PUNCHING, NO MANUAL LOGS",
    image: "/hrms.png",
    checkpoints: [
      "BIOMETRIC FACE SCAN",
      "CHECK-IN IN SECONDS",
      "NO PROXY ATTENDANCE",
      "MANAGER LIVE VISIBILITY",
      "MOBILE-FRIENDLY FLOW",
    ],
    href: "/hrms",
    linkLabel: "View HRMS",
  },
  {
    title: "EPF, ESIC & TDS",
    tagline: "STATUTORY FILING WITHOUT THE SPREADSHEETS",
    image: "/hrms.png",
    checkpoints: [
      "EPF CONTRIBUTION CALC",
      "ESIC COMPLIANCE READY",
      "TDS DEDUCTION AUTO",
      "FILING FROM PAYROLL RUN",
      "AUDIT-READY RECORDS",
    ],
    href: "/hrms",
    linkLabel: "View HRMS",
  },
  {
    title: "Integrations",
    tagline: "RAZORPAY, COMPLIANCE, AND PAYROLL RAILS",
    image: "/hrms.png",
    checkpoints: [
      "RAZORPAY DISBURSEMENT",
      "STATUTORY COMPLIANCE HOOKS",
      "THIRD-PARTY TOOL READY",
      "NO DUCT-TAPED STACK",
      "GO LIVE FASTER",
    ],
    href: "/book",
    linkLabel: "Book a demo",
  },
];
